# Generated by Django 6.0 on 2026-01-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_fees',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('membership', 'Membership fee'), ('event', 'Event fee'), ('other', 'Other')], default='membership', max_length=20)),
                ('period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.clubevents')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
            ],
            options={
                'ordering': ('-date_paid',),
            },
        ),
    ]
