# Generated by Django 5.0.7 on 2024-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_address_member_city_member_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
