# Generated by Django 5.0.7 on 2024-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('event', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
