# Generated by Django 5.0.7 on 2024-07-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
