# Generated by Django 5.0.7 on 2024-07-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='mystaticfiles/'),
        ),
    ]
