# Generated by Django 5.0.7 on 2024-07-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ClubPicture',
        ),
    ]
