# Generated by Django 5.0.7 on 2024-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_clubevents_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevents',
            name='event_members',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
