# Generated by Django 5.0.7 on 2024-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_clubevents_event_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevents',
            name='event_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
